---
# Creating multiple plays: https://www.middlewareinventory.com/blog/ansible-playbook-example/

# Play 1
- name: Deploy Application
  hosts: all
  tasks: 

    # Task D.2: Downloading & copying/extracting the app to the local ec2.
    - name: Download Servian Test App
      become: yes
      get_url:
        url: https://github.com/servian/TechTestApp/releases/download/v.0.6.0/TechTestApp_v.0.6.0_linux64.zip
        dest: /home/ec2-user
        mode: 0755 # Set permission of file
        
    - name: Extract the App to the ec2
      become: yes
      unarchive:
        src: /home/ec2-user/TechTestApp_v.0.6.0_linux64.zip
        dest: /home/ec2-user
        remote_src: yes # Tells cmd that the zip is already on the remote ec2: https://docs.ansible.com/ansible/latest/modules/unarchive_module.html

# Play 2
- name: Establish Database
  hosts: dbservers
  tasks:

    - name: Connect to Database
      become: yes
      become_method: sudo
      script:
        # chdir: ~/ # Setup our placement in the remote directory before running the script
        cmd: ../ansible/update_db.sh # Copy a local script to the remote directory, & run it.