---
# Creating multiple plays: https://www.middlewareinventory.com/blog/ansible-playbook-example/

# Play 1
- name: Deploy Application
  hosts: all
  tasks: 

    # Task D.2: Downloading & copying/extracting the app to the local ec2.
    - name: Download Servian Test App
      become: yes
      get_url:
        url: https://github.com/servian/TechTestApp/releases/download/v.0.6.0/TechTestApp_v.0.6.0_linux64.zip
        dest: /etc
        mode: 0755 # Set permission of file
        
    - name: Extract the App to the ec2
      become: yes
      unarchive:
        src: /etc/TechTestApp_v.0.6.0_linux64.zip
        dest: /etc
        remote_src: yes # Tells cmd that the zip is already on the remote ec2: https://docs.ansible.com/ansible/latest/modules/unarchive_module.html

# Play 2
- name: Establish Database
  hosts: dbservers
  tasks:

    # Install Local Service on Remote Host: https://stackoverflow.com/questions/40113964/how-can-i-install-a-systemd-service-using-ansible
    - name: Install Deployment Service on Remote Host
      become: yes
      template:
        src: create_service.tpl
        dest: /etc/systemd/system/servian.service

    # Execute Shell Script on Remote Hosts: https://stackoverflow.com/questions/21160776/how-to-execute-a-shell-script-on-a-remote-server-using-ansible
    - name: Connect to & Reload the Database
      become: yes
      become_method: sudo
      script:
        chdir: /etc # Setup our placement in the remote directory before running the script
        cmd: update_db.sh # Copy a local script to the remote directory, & run it.    

    - name: Deploy App Using Service
      become: yes
      systemd:
        name: servian # Name of the serivce added, without the '.service' part.
        state: started
        daemon_reload: yes # If the servian.service file is changed, this reloads the system to accomodate for changes.
        enabled: yes # Start service on booting the ec2

    - name: Update the Database with Tables
      become: yes
      command:
        chdir: /etc/dist
        cmd: ./TechTestApp updatedb -s